# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: GHCR 

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        
      #Build
      - id: buildx
        uses: docker/setup-buildx-action@v1
      
      #
      - name: Cache docker files
        uses: actions/cache@v2
        with: 
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: 
            ${{ runner.os }}-buildx-

      # Docker
      - name: Login to github
        if: github.event_name != 'pull request'
        
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io 
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PRUEBA_GITHUB_TOKEN }}
      
      # build y push
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.output.name }}
          push: true
          tags: ghcr.io/mfabian-na-at/mfab:1.1.0
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          
      #Digest
      - name: Image digest
        run: echo ${{ steps.docker_build.output.digest }}
