# This is a basic workflow to help you get started with Actions

name: CI to docker hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checamos el repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      # Docker
      - name: Login to Docker E
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      #Setup del Build
      - name: Configurar Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      #Build
      - name: Construir y empujar 
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mfab:1.1.0
      
      #Digest
      - name: Image digest
        run: echo ${{ steps.docker_build.output.digest }}
        
